### ISSUE TITLE
Use Rubocop configuration

### ISSUE THREAD

**Issue by Ana06** [sds/haml-lint#239]
For some cops, such as `LineLength`, could make sense to use Rubocop configuration, `Metrics/LineLength` maximum in this case . As I think it is a normal case to want that this two values are the same.

We could have something like:

```yaml
linters:
  LineLength:
    max: rubocop
```
