### ISSUE TITLE
LineLenght in todo are ignored with custom lenght in main

### ISSUE THREAD

**Issue by mtancoigne** [sds/haml-lint#311]
Hello

First, thank you for this gem, it helps us to keep our code clean.

I have an issue with LineLenght defined as follow:

```yaml
# .haml-lint.yml
---
inherits_from: .haml-lint_todo.yml

linters:
  LineLength:
    max: 120

# .haml-lint_todo.yml
linters:

  # Offense count: 3
  LineLength:
    exclude:
      - "app/views/devise/confirmations/new.html.haml"
      - "app/views/devise/registrations/edit.html.haml"
      - "app/views/devise/shared/_links.html.haml"
```

Given the configuration, we should expect these three files to be ignored by Haml-lint, but they are not:

```text
app/views/devise/confirmations/new.html.haml:7 [W] LineLength: Line is too long. [155/120]
app/views/devise/registrations/edit.html.haml:34 [W] LineLength: Line is too long. [127/120]
app/views/devise/shared/_links.html.haml:18 [W] LineLength: Line is too long. [137/120]
```

The issue occurs in Haml-lint `0.28` and `0.32`. I have not tested other versions.

Does that means the inherited configuration is overridden by the main configuration instead of being merged ?
