### ISSUE TITLE
Syntax linter ignores exclude

### ISSUE THREAD

**Issue by wintersolutions** [sds/haml-lint#330]
I have a configuration file:

```
linters:
  Syntax:
    exclude:
      - lib/templates/haml/scaffold/_form.html.haml
```

When I run `haml-lint` with it, it still reports:

`lib/templates/haml/scaffold/_form.html.haml:5 [E] Syntax: Illegal nesting: nesting within plain text is illegal.`

As a workaround I would love to put the file in the global exclude but this is a inherited file and the parent declares a global exclude already.
