### ISSUE TITLE
hamllint: warning W - RuboCop: Rails/HelperInstanceVariable: Do not use instance variables in helpers.

### ISSUE THREAD

**Issue by oslyak** [sds/haml-lint#331]
How to disable this rule in haml files?

In .haml-lint.yml
```
RuboCop:
  ignored_cops:
    - Rails/HelperInstanceVariable
    - HelperInstanceVariable

```

In .rubocop.yml 
```
Rails/HelperInstanceVariable:
  Enabled: false
```

But this rule still bother me

**Comment by oslyak** [comment]
In .haml-lint.yml

```
  RuboCop:
    enabled: true
    # These cops are incredibly noisy when it comes to HAML templates, so we
    # ignore them.
    ignored_cops:
      - Layout/TrailingEmptyLines
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Metrics/LineLength
      - Rails/HelperInstanceVariable
      - Style/AlignParameters
      - Style/BlockNesting
      - Style/FileName
      - Style/FinalNewline
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/IndentationWidth
      - Style/Next
      - Style/TrailingBlankLines
      - Style/TrailingWhitespace
      - Style/WhileUntilModifier
```
